apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bdcg3jvtx-nodejs 
  janus-idp.io/tekton: bdcg3jvtx-nodejs
  backstage.io/kubernetes-id: bdcg3jvtx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bdcg3jvtx-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  