apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bdcg3jvtx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bdcg3jvtx-nodejs 
  name: bdcg3jvtx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bdcg3jvtx-nodejs 
